# Catppuccin Frappe
foreground              #c6d0f5
background              #303446
selection_foreground    #303446
selection_background    #f2d5cf

cursor                  #f2d5cf
cursor_text_color       #303446

url_color               #f2d5cf

# Black
color0  #51576d
color8  #626880

# Red
color1  #e78284
color9  #e78284

# Green
color2  #a6d189
color10 #a6d189

# Yellow
color3  #e5c890
color11 #e5c890

# Blue
color4  #8caaee
color12 #8caaee

# Magenta
color5  #ca9ee6
color13 #ca9ee6

# Cyan
color6  #81c8be
color14 #81c8be

# White
color7  #b5bfe2
color15 #a5adce

font_family JetBrainsMono Nerd Font
font_size 12.0
window_padding_width 8
